### ISSUE TITLE
Panic when trying to select a list of records with slice of pointers

### ISSUE THREAD

**Issue by sdzyba** [gobuffalo/pop#385]
## Description

Query execution panics when trying to select a list of records with slice of pointers.

### Steps to Reproduce the Problem

Given there is a model:
```go
type User struct {
	ID        int64     `json:"id" db:"id"`
	Name      string    `json:"name" db:"name"`
	CreatedAt time.Time `json:"created_at" db:"created_at"`
	UpdatedAt time.Time `json:"updated_at" db:"updated_at"`
}
```

And we try to select all users:
```go
users := []*models.User{}
err := models.DB.All(&users)
```

### Expected Behavior

Expected `users` variable to be populated with user records.

### Actual Behavior

I got a panic:
```
panic: reflect: FieldByName of non-struct type

goroutine 1 [running]:
reflect.(*rtype).FieldByName(0xb52800, 0xc251a3, 0x10, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/type.go:942 +0x135
github.com/gobuffalo/pop/associations.ForStruct(0xc0001766c0, 0xc00029c240, 0xc000021f50, 0x1, 0x1, 0x196, 0xc000000300, 0x3, 0xc000030570, 0xc000030500)
	/go/pkg/mod/github.com/gobuffalo/pop@v4.11.0+incompatible/associations/associations_for_struct.go:63 +0x28c
github.com/gobuffalo/pop.(*Query).eagerAssociations(0xc000165d38, 0xc0001766c0, 0xc00029c240, 0xc000176601, 0xc0001766c0)
	/go/pkg/mod/github.com/gobuffalo/pop@v4.11.0+incompatible/finders.go:207 +0x2df
github.com/gobuffalo/pop.(*Query).eagerAssociations(0xc000165d38, 0xafe660, 0xc0002a7120, 0xc000165b38, 0x0)
	/go/pkg/mod/github.com/gobuffalo/pop@v4.11.0+incompatible/finders.go:199 +0x24b
github.com/gobuffalo/pop.(*Query).All(0xc000165d38, 0xafe660, 0xc0002a7120, 0x1, 0xc000345740)
	/go/pkg/mod/github.com/gobuffalo/pop@v4.11.0+incompatible/finders.go:149 +0xd2
github.com/gobuffalo/pop.(*Connection).All(...)
	/go/pkg/mod/github.com/gobuffalo/pop@v4.11.0+incompatible/finders.go:124
gitlab.com/project/api/actions.App(0xc0001abf88)
	/service/actions/app.go:97 +0x1ac
main.main()
	/service/main.go:16 +0x22
```

When using a slice of structs `[]models.User{}` it works as expected.

### Info

macOS 10.14.4, go1.12.3 darwin/amd64, buffalo v0.14.4, pop v4.11.0

**Comment by stanislas-m** [comment]
@sdzyba Can I ask you to try with the development branch version?

**Comment by sdzyba** [comment]
@stanislas-m 
It seems I messed up a bit with my report. The issue is with eager loading.
```
type Users []*User

type User struct {
	// fields
	Accounts UserAccounts `has_many:"user_accounts"`
}

type UserAccounts []*UserAccount

type UserAccount struct {
	// fields
	User *User `belongs_to:"user"`
}
```

Query:
```
users := models.Users{}
err := models.DB.Eager("Accounts").All(&users)
```

Using pop v4.11.0:
When `Users` is `[]*User` it fails with panic I printed in my first message.
When `Users` is `[]User` it works.
Without `Eager("Accounts")` both options work.

Using pop `development`:
When `Users` is `[]*User` it returns error `could not retrieve associations: could not get struct associations: not a struct`, although it populates the `users` variable, but doesn't preload Accounts.
When `Users` is `[]User` it works.
Without `Eager("Accounts")` both options work.

**Comment by sdzyba** [comment]
Full error for `development` version:
```
could not get struct associations: not a struct
could not retrieve associations
github.com/gobuffalo/pop.(*Query).eagerAssociations
	/go/pkg/mod/github.com/gobuffalo/pop@v4.10.1-0.20190603121931-96a54f4371d5+incompatible/finders.go:209
github.com/gobuffalo/pop.(*Query).eagerAssociations
	/go/pkg/mod/github.com/gobuffalo/pop@v4.10.1-0.20190603121931-96a54f4371d5+incompatible/finders.go:199
github.com/gobuffalo/pop.(*Query).All
	/go/pkg/mod/github.com/gobuffalo/pop@v4.10.1-0.20190603121931-96a54f4371d5+incompatible/finders.go:149
github.com/gobuffalo/pop.(*Connection).All
	/go/pkg/mod/github.com/gobuffalo/pop@v4.10.1-0.20190603121931-96a54f4371d5+incompatible/finders.go:124
gitlab.com/project/api/actions.App
	/service/actions/app.go:97
main.main
	/service/main.go:16
runtime.main
	/usr/local/go/src/runtime/proc.go:200
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1337
```

**Comment by stanislas-m** [comment]
@sdzyba I just pushed a new fix on the development branch, can you try it? Thanks!

**Comment by sdzyba** [comment]
@stanislas-m 
It works. Thanks a lot.
