### ISSUE TITLE
value of type time.Time is not assignable to type null.Time

### ISSUE THREAD

**Issue by maxbry** [gobuffalo/pop#627]
Hello,

I have the following model:

    type Car struct {
        ID int `json:"id" db:"id"`
        CreatedAt null.Time `json:"created_at" db:"created_at"`
        [...]
    }

I'm creating an object the following way:

    car := &models.Car{}
    car.name = "test name"
    models.db.Create(car)

Which gives the following error:
```
panic: reflect.Set: value of type time.Time is not assignable to type null.Time

goroutine 1 [running]:
reflect.Value.assignTo(0x4b85bc0, 0xc0000b9e00, 0x99, 0x4b9d493, 0xb, 0x4b33580, 0x0, 0xc0001a58a0, 0xc0000b9e00, 0xc0000b9e00)
	/usr/local/Cellar/go/1.15.7_1/libexec/src/reflect/value.go:2435 +0x405
reflect.Value.Set(0x4b33580, 0xc00081a588, 0x199, 0x4b85bc0, 0xc0000b9e00, 0x99)
	/usr/local/Cellar/go/1.15.7_1/libexec/src/reflect/value.go:1564 +0xbd
github.com/gobuffalo/pop.(*Model).touchCreatedAt(0xc00082eed0)
	/home/dev/Programming/golang/pkg/mod/github.com/gobuffalo/pop@v4.13.1+incompatible/model.go:175 +0x2b3
github.com/gobuffalo/pop.(*Connection).Create.func1.1(0xc0026f34a34de720, 0x203e25f21)
	/home/dev/Programming/golang/pkg/mod/github.com/gobuffalo/pop@v4.13.1+incompatible/executors.go:237 +0x24e
github.com/gobuffalo/pop.(*Connection).timeFunc(0xc000096120, 0x4b961d8, 0x6, 0xc0001a5ba0, 0xc0001a5be0, 0x4793c55)
	/home/dev/Programming/golang/pkg/mod/github.com/gobuffalo/pop@v4.13.1+incompatible/connection.go:211 +0x50
github.com/gobuffalo/pop.(*Connection).Create.func1(0xc00082eed0, 0xc00082ee00, 0xc0026f34a08bb5f8)
	/home/dev/Programming/golang/pkg/mod/github.com/gobuffalo/pop@v4.13.1+incompatible/executors.go:175 +0xae
github.com/gobuffalo/pop.(*Model).iterate(0xc00082eed0, 0xc0001a5ca0, 0xc000096120, 0x4b94f66)
	/home/dev/Programming/golang/pkg/mod/github.com/gobuffalo/pop@v4.13.1+incompatible/model.go:222 +0x292
github.com/gobuffalo/pop.(*Connection).Create(0xc000096120, 0x4aee6e0, 0xc00081a580, 0x0, 0x0, 0x0, 0xc000818600, 0x0)
	/home/dev/Programming/golang/pkg/mod/github.com/gobuffalo/pop@v4.13.1+incompatible/executors.go:174 +0x105
project.com/buffalo_database/grifts.MigrateSDBIntents(0xc000096120, 0xff, 0x0, 0x0, 0x0)
	/home/dev/Programming/golang/src/project.com/buffalo_database/grifts/migrate.go:98 +0x572
project.com/buffalo_database/grifts.glob..func20.1(0xc0004f8050, 0xc000112180, 0x7ffeefbffad9)
	/home/dev/Programming/golang/src/project.com/buffalo_database/grifts/migrate.go:113 +0x6a
github.com/markbates/grift/grift.Run(0x7ffeefbffad9, 0xf, 0xc0004f8050, 0x0, 0x0)
	/home/dev/Programming/golang/pkg/mod/github.com/markbates/grift@v1.5.0/grift/grift.go:144 +0x11e
github.com/markbates/grift/grift.Exec(0xc00000e090, 0x1, 0x1, 0x0, 0x0, 0x0)
	/home/dev/Programming/golang/pkg/mod/github.com/markbates/grift@v1.5.0/grift/grift.go:173 +0x185
main.main()
	/home/dev/Programming/golang/src/project.com/buffalo_database/.grifter/main.go:14 +0x9b
```

How can I fix this?

**Comment by sio4** [comment]
Cannot identify what is `null.Time`. Could you please explain some more or provide a sample code set? Otherwise, I would like to close this issue within a few days.
